import type { Metadata } from "next";
import GenreProvider from "./_components/ask-genre";

export const metadata: Metadata = {
  title: "dashbord page",
  description: "Generated by create next app",
};

export default async function DashbordLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <GenreProvider>{children}</GenreProvider>
    </div>
  );
}
