import "@/assets/css/main.css";
import 'react-toastify/dist/ReactToastify.css';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/layouts/header";
import { ModalProvider } from "@/components/ui/modal/modal.context";
import { SearchProvider } from "@/components/ui/search/search.context";
import ManagedModal from "@/components/ui/modal/managed-modal";
import { ReactNode } from "react";
import PrivateRoute from "@/lib/private-route";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SearchProvider>
          <ModalProvider>
            <ManagedModal />
            <Header />
            <PrivateRoute>{children}</PrivateRoute>
          </ModalProvider>
        </SearchProvider>
      </body>
    </html>
  );
}
